"*.{md,html,css,yml,yaml,json}": "prettier --write"
".eslintrc.js": "prettier --write"
"./!(.eslintrc).{js,ts}": "pnpm run lint:fix"
"api/*.{js,ts}": "pnpm run lint:fix"
"*.{png,jpeg,jpg,gif,svg}": "imagemin-lint-staged"
